---
- name: Automember absent example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure group automember rule admins is absent
    ipaautomember:
      name: admins
      type: group
      state: absent

  - name: Ensure hostgroup automember rule ipaservers is absent
    ipaautomember:
      name: ipaservers
      type: hostgroup
      state: absent